#[bastionhost]
#bastion-host ansible_host=158.160.159.69 ansible_ssh_user=sergey
#
#[webservers]
#web1 ansible_host=192.168.1.3
#web2 ansible_host=192.168.2.3
#
#[prometheus]
#prometheus-host ansible_host=192.168.3.3
#
#[grafana]
#grafana-host ansible_host=192.168.3.5
#
#[elasticsearch]
#elasticsearch-host ansible_host=192.168.1.4
#
#[kibana]
#kibana-host ansible_host=192.168.3.6 
#
#[webservers:vars]
#ansible_ssh_user=sergey
#ansible_ssh_common_args='-o ProxyCommand="ssh -W %h:%p sergey@158.160.159.69"'
#
#[prometheus:vars]
#ansible_ssh_user=sergey
#ansible_ssh_common_args='-o ProxyCommand="ssh -W %h:%p sergey@158.160.159.69"'
#
#[grafana:vars]
#ansible_ssh_user=sergey
#ansible_ssh_common_args='-o ProxyCommand="ssh -W %h:%p sergey@158.160.159.69"'
#
#[elasticsearch:vars]
#ansible_ssh_user=sergey
#ansible_ssh_common_args='-o ProxyCommand="ssh -W %h:%p sergey@158.160.159.69"'
#
#[kibana:vars]
#ansible_ssh_user=sergey
#ansible_ssh_common_args='-o ProxyCommand="ssh -W %h:%p sergey@158.160.159.69"'
all:
  children:
    webservers:
      hosts:
        web-server1.ru-central1.internal:
          ansible_host: "192.168.1.3"
        web-server2.ru-central1.internal:
          ansible_host: "192.168.2.3"
      vars:
        ansible_user: sergey
        ansible_ssh_common_args: '-o ProxyCommand="ssh -W %h:%p -q sergey@158.160.185.236"'

    zabbix:
      hosts:
        zabbix.ru-central1.internal:
          ansible_host: "192.168.3.7"
      vars:
        ansible_user: sergey
        ansible_ssh_common_args: '-o ProxyCommand="ssh -W %h:%p -q sergey@158.160.185.236"'

    elasticsearch:
      hosts:
        elasticsearch.ru-central1.internal:
          node_name: es-node-1
          ansible_host: "192.168.1.4"
      vars:
        ansible_user: sergey
        ansible_ssh_common_args: '-o ProxyCommand="ssh -W %h:%p -q sergey@158.160.185.236"'

    kibana:
      hosts:
        kibana.ru-central1.internal:
          ansible_host: "192.168.3.6"
      vars:
        ansible_user: sergey
        ansible_ssh_common_args: '-o ProxyCommand="ssh -W %h:%p -q sergey@158.160.185.236"'

    bastion:
      hosts:
        bastion-host.ru-central1.internal:
          ansible_host: "192.168.3.100"
      vars:
        ansible_user: sergey