---
- name: Configure Zabbix server
  hosts: zabbix
  become: yes
  vars_files:
    - ../group_vars/all.yml
  tasks:
    - name: Install required packages
      apt:
        name:
          - gzip
          - apache2
          - php
          - php-mysql
          - php-ldap
          - php-bcmath
          - php-mbstring
          - php-gd
          - php-xml
          - php-mysql
          - mysql-server
          - php8.1 
          - php8.1-fpm 
          - php8.1-mysql 
          - php8.1-ldap 
          - php8.1-bcmath 
          - php8.1-mbstring 
          - php8.1-gd 
          - php8.1-xml
        state: present
        update_cache: yes

    - name: Download Zabbix GPG key
      ansible.builtin.get_url:
        url: https://repo.zabbix.com/zabbix-official-repo.key
        dest: /etc/apt/trusted.gpg.d/zabbix_official_repo.asc
        mode: '0644'

    - name: Add Zabbix repository
      ansible.builtin.apt_repository:
        repo: "deb [signed-by=/etc/apt/trusted.gpg.d/zabbix_official_repo.asc] http://repo.zabbix.com/zabbix/7.0/ubuntu jammy main"
        state: present
        update_cache: yes

    - name: Install Zabbix server
      apt:
        name:
          - zabbix-server-mysql
          - zabbix-frontend-php
          - zabbix-apache-conf
          - zabbix-sql-scripts
          - zabbix-agent
        state: present
        update_cache: yes

    - name: Install python3 and pip3
      apt:
        name:
          - python3
          - python3-pip
        state: present
        update_cache: yes

    - name: Install PyMySQL Python library
      pip:
        name: PyMySQL
        executable: pip3

    - name: Start and enable MySQL
      systemd:
        name: mysql
        state: started
        enabled: yes

    - name: Create Zabbix database
      mysql_db:
        name: zabbix
        state: present
        login_unix_socket: /var/run/mysqld/mysqld.sock

    - name: Create Zabbix user
      mysql_user:
        name: zabbix
        password: "{{ zabbix_db_password }}"
        priv: 'zabbix.*:ALL'
        host: localhost
        state: present
        login_unix_socket: /var/run/mysqld/mysqld.sock

    - name: Import Zabbix database schema
      shell: zcat /usr/share/doc/zabbix-sql-scripts/mysql/server.sql.gz | mysql -uzabbix -p{{ zabbix_db_password }} zabbix
      args:
        creates: /var/lib/mysql/zabbix/schema.ibd

    - name: Configure Zabbix server
      template:
        src: ../templates/zabbix_server.conf.j2
        dest: /etc/zabbix/zabbix_server.conf
        mode: '0644'
      notify: restart zabbix-server

    - name: Configure PHP for Zabbix
      template:
        src: ../templates/php.ini.j2
        dest: /etc/php/8.1/fpm/php.ini
        mode: '0644'
      notify: restart apache2

    - name: Start and enable services
      systemd:
        name: "{{ item }}"
        state: started
        enabled: yes
      with_items:
        - zabbix-server
        - zabbix-agent
        - apache2

  handlers:
    - name: restart zabbix-server
      systemd:
        name: zabbix-server
        state: restarted

    - name: restart apache2
      systemd:
        name: apache2
        state: restarted 